// <auto-generated />
namespace BGoodMusic.EFDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class S2_AddUserInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(S2_AddUserInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201410260004036_S2_AddUserInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
